name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: ./web
        remote_path: /var/www/
        remote_host: karanvani.live
        remote_user: github
        remote_key: ${{ secrets.DEPLOYKEY }}
